mykey = "firstkey"
ami = "ami-0889a44b331db0194"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "petclinic-jenkins-server-secgr-v1"
jenkins-server-tag = "Jenkins Server of Petclinic v1"
jenkins-profile = "petclinic-jenkins-server-profile v1"
jenkins-role = "petclinic-jenkins-server-role-v1"